services:
  tei-gpu:
    image: ghcr.io/huggingface/text-embeddings-inference:120-1.9
    command: ["--model-id", "/data/BAAI/bge-m3", "--auto-truncate"]
    volumes:
      - tei_data:/data
volumes:
  tei_data:
