services:
  tei-gpu:
    image: ghcr.io/huggingface/text-embeddings-inference:86-1.7
    command: ["--model-id", "/data/BAAI/bge-m3", "--auto-truncate"]
    volumes:
      - tei_data:/data
  tei-rerank:
    profiles:
      - tei-gpu
    image: ghcr.io/huggingface/text-embeddings-inference:86-1.7
    hostname: tei-rerank
    ports:
      - 6381:80
    networks:
      - ragflow
    command: ["--model-id", "/data/BAAI/bge-reranker-v2-m3", "--auto-truncate"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - tei_rerank_data:/data
    restart: unless-stopped
volumes:
  tei_data:
  tei_rerank_data:
